import { useState, useEffect, useRef } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import * as THREE from 'three';
import { Canvas, useFrame } from '@react-three/fiber'
import {
  Html,
  Sky,
  Cloud,
  PerspectiveCamera,
  OrbitControls,
  Environment,
  Lightformer,
} from "@react-three/drei";




const Camera = () => {
  const perspectiveCamera = useRef(null);
  const orbitControls = useRef(null);

  useEffect(() => {
    console.log(perspectiveCamera);
    console.log(orbitControls);
  }, [])

  return (
    <>
      <PerspectiveCamera
        ref={perspectiveCamera}
        makeDefault
        position={[0, 0, 5]} />
      <OrbitControls
        ref={orbitControls}
        autoRotate={true}
        autoRotateSpeed={1}
        zoomSpeed={0.2}
      />
    </>
  )
}


const Light = () => {
  return (
    <>
      <ambientLight intensity={1} />
      <spotLight position={[2, 3, 2]} intensity={1} angle={8} castShadow />
    </>
  )
}


const Object = ({ color, setColor }) => {
  const threeText = useRef(null);
  console.log(threeText)

  return (
    <>
      <mesh position={[0, -1, 0]} rotation={[-Math.PI / 2, 0, 0]} receiveShadow>
        <boxGeometry args={[1000, 1000, 0.2]} />
        <meshStandardMaterial />
      </mesh>

      <mesh castShadow>
        <boxGeometry />
        {color == false &&
          <meshStandardMaterial color={"#333"} /> || <meshStandardMaterial color={"blue"} />
        }
        <meshStandardMaterial color={"#333"} />
      </mesh>
    </>
  )
}


const Static = () => {
  return (
    <Html>
      <h1>Hello Metaverse</h1>
      <p>This is some example at an early stage.</p>
    </Html>
  )
}


export default function Home() {

  const [color, setColor] = useState(false);
  const changeColor = () => {
    setColor(() => !false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <button type="button" onClick={() => changeColor()}></button>
      </nav>

      <main>
        <Canvas shadows>
          <Camera />
          <Light />

          <Object />
          <Static />

          <Sky distance={450000} sunPosition={[0, 1, 0]} inclination={1} azimuth={0.25} />
          {/* <Cloud
            opacity={0.8}
            speed={0.4} // Rotation speed
            width={10} // Width of the full cloud
            depth={1.5} // Z-dir depth
            segments={20} // Number of particles
          /> */}

          <Environment background>
            <Lightformer
              form="rect" // circle | ring | rect (optional, default = rect)
              intensity={1} // power level (optional = 1)
              color="white" // (optional = white)
              scale={[10, 5]} // Scale it any way you prefer (optional = [1, 1])
              target={[0, 0, 0]} // Target position (optional = undefined)
            />
            <mesh>
              <sphereGeometry args={[50, 50, 50]} />
              <meshBasicMaterial color={"white"} side={THREE.BackSide} />
            </mesh>
          </Environment>


        </Canvas>
      </main>
    </>
  )
}
